/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hu_sandorfehervari_analogdisplayreader_DisplayDetectorJNI */

#ifndef _Included_hu_sandorfehervari_analogdisplayreader_DisplayDetectorJNI
#define _Included_hu_sandorfehervari_analogdisplayreader_DisplayDetectorJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hu_sandorfehervari_analogdisplayreader_DisplayDetectorJNI
 * Method:    processImage
 * Signature: (Ljava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_hu_sandorfehervari_analogdisplayreader_DisplayDetectorJNI_processImage
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
